[package]
name = "rsx-macro"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
parser = { path = "../parser", version = "0.1.0" }
proc-macro2 = "1.0.94"
quote = "1.0.40"
syn = { version = "2.0.100", features = ["fold", "visit"] }
heck = "0.5"
