[package]
name = "parser"
version = "0.1.0"
edition = "2024"

[dependencies]
dominator = "0.5.38"
futures-signals = "0.3.34"
strum = { version = "0.27.1", features = ["derive"] }
syn = "2.0.100"
web-sys = "0.3.77"
macros = { path = "../macros" }
proc-macro2 = "1.0.94"
